package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Vibrant Palette - Teal / Deep Cyan & Slate (Light Theme)
val VibrantPrimary = Color(0xFF006874)
val VibrantOnPrimary = Color(0xFFFFFFFF)
val VibrantPrimaryContainer = Color(0xFFDCE3E9)
val VibrantOnPrimaryContainer = Color(0xFF001F24)
val VibrantSecondary = Color(0xFF3F484B)
val VibrantSecondaryContainer = Color(0xFFF1F4F9)
val VibrantOnSecondary = Color(0xFFFFFFFF)
val VibrantTertiary = Color(0xFF70787D)
val VibrantBackground = Color(0xFFF7F9FC)
val VibrantSurface = Color(0xFFFFFFFF)
val VibrantOnBackground = Color(0xFF191C1E)
val VibrantOnSurface = Color(0xFF191C1E)
val VibrantSurfaceVariant = Color(0xFFE5EBEF)
val VibrantOutline = Color(0xFFC1C7CE)
val VibrantError = Color(0xFFB3261E)

// Vibrant Palette (Dark Theme equivalents)
val VibrantDarkPrimary = Color(0xFF80D4E3)
val VibrantDarkOnPrimary = Color(0xFF00363D)
val VibrantDarkPrimaryContainer = Color(0xFF004F58)
val VibrantDarkOnPrimaryContainer = Color(0xFFE0F3F8)
val VibrantDarkSecondary = Color(0xFFB0CBCF)
val VibrantDarkSecondaryContainer = Color(0xFF344A4D)
val VibrantDarkBackground = Color(0xFF191C1E)
val VibrantDarkSurface = Color(0xFF222628)
val VibrantDarkOnBackground = Color(0xFFE1E3E4)
val VibrantDarkOnSurface = Color(0xFFE1E3E4)
val VibrantDarkSurfaceVariant = Color(0xFF3F484B)
val VibrantDarkOutline = Color(0xFF8B9296)
val VibrantDarkError = Color(0xFFFFB4AB)
